services:
  - type: web
    name: taiwan-stock-timeout-fixed
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    healthCheckPath: /api/health

